// SPDX-License-Identifier: AGPL-3.0-or-later
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::PathBuf;

// ─── Run mode ───────────────────────────────────────────────────────────────

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum RunMode {
    Docker,
    Native,
}

impl Default for RunMode {
    fn default() -> Self {
        if cfg!(target_os = "macos") {
            RunMode::Native
        } else {
            RunMode::Docker
        }
    }
}

// ─── GPU types ──────────────────────────────────────────────────────────────

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum GpuBackend {
    Local,
    Modal,
    Mps,
}

impl Default for GpuBackend {
    fn default() -> Self {
        GpuBackend::Local
    }
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct GpuDeviceConfig {
    pub index: u32,
    pub enabled: bool,
    pub utilization: u8,
    pub yielding: bool,
}

impl Default for GpuDeviceConfig {
    fn default() -> Self {
        GpuDeviceConfig {
            index: 0,
            enabled: true,
            utilization: 80,
            yielding: false,
        }
    }
}

// ─── QPU / D-Wave ───────────────────────────────────────────────────────────

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct DwaveConfig {
    pub token: String,
    #[serde(default = "default_dwave_solver")]
    pub solver: String,
    #[serde(default = "default_dwave_region_url")]
    pub dwave_region_url: String,
    pub daily_budget: String,
    #[serde(default)]
    pub qpu_min_blocks_for_estimation: Option<u32>,
    #[serde(default)]
    pub qpu_ema_alpha: Option<f64>,
}

fn default_dwave_solver() -> String {
    "Advantage2_System1.13".to_string()
}
fn default_dwave_region_url() -> String {
    "https://na-west-1.cloud.dwavesys.com/sapi/v2/".to_string()
}

impl Default for DwaveConfig {
    fn default() -> Self {
        DwaveConfig {
            token: String::new(),
            solver: default_dwave_solver(),
            dwave_region_url: default_dwave_region_url(),
            daily_budget: String::new(),
            qpu_min_blocks_for_estimation: None,
            qpu_ema_alpha: None,
        }
    }
}

// ─── Defaults ───────────────────────────────────────────────────────────────

fn default_port() -> u16 { 20049 }
fn default_listen() -> String { "::".to_string() }
fn default_num_cpus() -> u32 { 1 }
fn default_timeout() -> u32 { 3 }
fn default_heartbeat_interval() -> u32 { 15 }
fn default_heartbeat_timeout() -> u32 { 300 }
fn default_log_level() -> String { "info".to_string() }
fn default_genesis_config() -> String {
    "genesis_block.json".to_string()
}
fn default_tofu() -> bool { true }
fn default_trust_db() -> String { "~/.quip/trust.db".to_string() }
fn default_rest_host() -> String { "127.0.0.1".to_string() }
fn default_rest_port() -> i16 { -1 }
fn default_telemetry_enabled() -> bool { true }
fn default_telemetry_dir() -> String { "telemetry".to_string() }

// ─── Node config ────────────────────────────────────────────────────────────

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct NodeConfig {
    // Network
    #[serde(default = "default_port")]
    pub port: u16,
    #[serde(default = "default_listen")]
    pub listen: String,
    #[serde(default)]
    pub public_host: String,
    #[serde(default)]
    pub public_port: Option<u16>,
    #[serde(default)]
    pub node_name: String,
    #[serde(default)]
    pub peers: Vec<String>,
    #[serde(default)]
    pub auto_mine: bool,

    // Identity
    #[serde(default)]
    pub secret: String,
    #[serde(default = "default_genesis_config")]
    pub genesis_config: String,

    // Trust
    #[serde(default = "default_tofu")]
    pub tofu: bool,
    #[serde(default = "default_trust_db")]
    pub trust_db: String,

    // TLS (empty = self-signed auto-generated by protocol)
    #[serde(default)]
    pub tls_cert_file: String,
    #[serde(default)]
    pub tls_key_file: String,
    #[serde(default)]
    pub verify_tls: bool,

    // REST API (disabled by default: port < 0)
    #[serde(default = "default_rest_host")]
    pub rest_host: String,
    #[serde(default = "default_rest_port")]
    pub rest_port: i16,
    #[serde(default = "default_rest_port")]
    pub rest_insecure_port: i16,

    // Telemetry
    #[serde(default = "default_telemetry_enabled")]
    pub telemetry_enabled: bool,
    #[serde(default = "default_telemetry_dir")]
    pub telemetry_dir: String,

    // Logging
    #[serde(default = "default_log_level")]
    pub log_level: String,
    #[serde(default)]
    pub node_log: String,
    #[serde(default)]
    pub http_log: String,

    // CPU mining
    #[serde(default = "default_num_cpus")]
    pub num_cpus: u32,

    // GPU mining
    #[serde(default)]
    pub gpu_backend: GpuBackend,
    #[serde(default)]
    pub gpu_device_configs: Vec<GpuDeviceConfig>,

    // D-Wave QPU
    #[serde(default)]
    pub dwave_config: Option<DwaveConfig>,

    // Advanced
    #[serde(default = "default_timeout")]
    pub timeout: u32,
    #[serde(default = "default_heartbeat_interval")]
    pub heartbeat_interval: u32,
    #[serde(default = "default_heartbeat_timeout")]
    pub heartbeat_timeout: u32,
    #[serde(default)]
    pub fanout: Option<u32>,
}

impl Default for NodeConfig {
    fn default() -> Self {
        NodeConfig {
            port: 20049,
            listen: "::".to_string(),
            public_host: String::new(),
            public_port: None,
            node_name: String::new(),
            peers: vec![],
            auto_mine: false,
            secret: String::new(),
            genesis_config: "genesis_block.json".to_string(),
            tofu: true,
            trust_db: "~/.quip/trust.db".to_string(),
            tls_cert_file: String::new(),
            tls_key_file: String::new(),
            verify_tls: false,
            rest_host: "127.0.0.1".to_string(),
            rest_port: -1,
            rest_insecure_port: -1,
            telemetry_enabled: true,
            telemetry_dir: "telemetry".to_string(),
            log_level: "info".to_string(),
            node_log: String::new(),
            http_log: String::new(),
            num_cpus: 1,
            gpu_backend: GpuBackend::Local,
            gpu_device_configs: vec![],
            dwave_config: None,
            timeout: 3,
            heartbeat_interval: 15,
            heartbeat_timeout: 300,
            fanout: None,
        }
    }
}

// ─── App settings ───────────────────────────────────────────────────────────

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct AppSettings {
    pub node_config: NodeConfig,
    pub active_tab: String,
    pub window_maximized: bool,
    pub image_tag: String,
    #[serde(default)]
    pub run_mode: RunMode,
    #[serde(default)]
    pub auto_update_enabled: bool,
}

impl Default for AppSettings {
    fn default() -> Self {
        AppSettings {
            node_config: NodeConfig::default(),
            active_tab: "status".to_string(),
            window_maximized: false,
            image_tag: "cpu".to_string(),
            run_mode: RunMode::default(),
            auto_update_enabled: false,
        }
    }
}

// ─── Container status ───────────────────────────────────────────────────────

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct ContainerStatus {
    pub running: bool,
    pub container_id: Option<String>,
    pub image: String,
    pub status_text: String,
}

/// Bootstrap config stored at a fixed OS-standard location.
/// Only contains the storage directory path override.
#[derive(Serialize, Deserialize, Default)]
struct BootstrapConfig {
    #[serde(default)]
    data_dir: Option<String>,
}

fn bootstrap_path() -> PathBuf {
    let config = dirs::config_dir()
        .unwrap_or_else(|| dirs::home_dir().unwrap().join(".config"));
    config.join("quip-node-manager").join("bootstrap.json")
}

fn load_bootstrap() -> BootstrapConfig {
    fs::read_to_string(bootstrap_path())
        .ok()
        .and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or_default()
}

fn save_bootstrap(cfg: &BootstrapConfig) -> Result<(), String> {
    let path = bootstrap_path();
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    let content = serde_json::to_string_pretty(cfg)
        .map_err(|e| e.to_string())?;
    fs::write(path, content).map_err(|e| e.to_string())
}

fn default_data_dir() -> PathBuf {
    dirs::home_dir()
        .expect("cannot determine home directory")
        .join("quip-data")
}

pub fn data_dir() -> PathBuf {
    let bootstrap = load_bootstrap();
    match bootstrap.data_dir {
        Some(ref p) if !p.is_empty() => PathBuf::from(p),
        _ => default_data_dir(),
    }
}

pub fn ensure_data_dir() -> Result<(), String> {
    fs::create_dir_all(data_dir()).map_err(|e| e.to_string())
}

fn settings_path() -> PathBuf {
    data_dir().join("app-settings.json")
}

pub fn load_settings() -> AppSettings {
    let path = settings_path();
    let mut settings = if let Ok(content) = fs::read_to_string(&path) {
        serde_json::from_str(&content).unwrap_or_default()
    } else {
        AppSettings::default()
    };
    // Native mode is only supported on macOS
    if !cfg!(target_os = "macos") {
        settings.run_mode = RunMode::Docker;
    }
    settings
}

pub fn save_settings(settings: &AppSettings) -> Result<(), String> {
    ensure_data_dir()?;
    let content =
        serde_json::to_string_pretty(settings)
            .map_err(|e| e.to_string())?;
    fs::write(settings_path(), content).map_err(|e| e.to_string())
}

#[tauri::command]
pub async fn get_settings() -> Result<AppSettings, String> {
    Ok(load_settings())
}

#[tauri::command]
pub async fn update_settings(
    mut settings: AppSettings,
) -> Result<(), String> {
    // Native mode is only supported on macOS
    if !cfg!(target_os = "macos") {
        settings.run_mode = RunMode::Docker;
    }
    save_settings(&settings)
}

#[tauri::command]
pub async fn is_first_boot() -> bool {
    !bootstrap_path().exists()
}

#[tauri::command]
pub async fn get_default_data_dir() -> Result<String, String> {
    Ok(default_data_dir().to_string_lossy().to_string())
}

#[tauri::command]
pub async fn get_data_dir() -> Result<String, String> {
    Ok(data_dir().to_string_lossy().to_string())
}

#[tauri::command]
pub async fn restart_app(app: tauri::AppHandle) {
    app.restart();
}

#[tauri::command]
pub async fn set_data_dir(path: String) -> Result<(), String> {
    let new_dir = if path.is_empty() {
        None
    } else {
        // Validate path is writable
        let p = PathBuf::from(&path);
        fs::create_dir_all(&p).map_err(|e| {
            format!("Cannot create directory {}: {}", path, e)
        })?;
        Some(path)
    };
    save_bootstrap(&BootstrapConfig { data_dir: new_dir })
}
